### ISSUE TITLE
Split Cards not supported

### ISSUE THREAD

**Issue by parrisha** [fecet/moxtrice#1]
It looks like that, in order to support Modal DFCs, this line removes the second half of split card names:
https://github.com/fecet/moxtrice/blob/ace42c3a159e498686ee28b3e644adf86e67f556/moxtrice/core.py#L151

I fixed this locally by changing this line to:

```
        MTGCard(name.split(" // ")[0], attr["quantity"]) if attr["card"]["layout"]!="split"
        else MTGCard(name, attr["quantity"])
```

Which appears to solve the issue

**Comment by fecet** [comment]
This is a known issue with cockatrice as it does not treat all "dual name cards" equally. To test this, I have created a list which can be found at https://www.moxfield.com/decks/SM3kDqILJUWolEUqr4C_rQ. 
https://github.com/fecet/moxtrice/blob/31bd49d2ac04462de8ee961422fab28ddc73a391/README.md?plain=1#L72

Some of the cards only appear with their first name while others are displayed with their full name, as shown in the image below:

![image](https://user-images.githubusercontent.com/41792945/234536613-61264b7d-1546-46ad-a49c-1afa967bc905.png)
I have observed that this behavior seems to be consistent with the type of "dual card". For instance, merged and adventure cards should be imported as their full name while transform cards should be imported using their original version. I intend to investigate this issue further.

**Comment by parrisha** [comment]
Thanks for linking the test deck - if you change line 151 as follows:

```
        MTGCard(name.split(" // ")[0], attr["quantity"]) if not (attr["card"]["layout"]=="split" or attr["card"]["layout"]=="adventure")
        else MTGCard(name, attr["quantity"]
```


Then this is the result for the moxtrice_test deck:

![image](https://user-images.githubusercontent.com/28071699/234584628-93a295c5-8be0-4067-a6b0-24c28d2b1d61.png)

**Comment by fecet** [comment]
Thanks for finding this！Feel free to reopen if three are further problems.
