### ISSUE TITLE
Local Variable Issue on Running

### ISSUE THREAD

**Issue by ThePoetics** [fecet/moxtrice#2]
Whenever I attempt to run moxtrice I receive the following error on my command-line (Windows 10, Python 3.11.5)

![image](https://github.com/fecet/moxtrice/assets/87587068/881e68b4-f247-4e38-b0ab-92f69eb43602)

When I attempt to run it from D: (where Python is installed), I instead get the following

![image](https://github.com/fecet/moxtrice/assets/87587068/5f53d219-51f7-4f10-b0a6-1d9199430e29)

Any assistance would be most appreciated!

**Comment by fecet** [comment]
Hello, thanks for reporting. Did you use moxtrice from pypi?

**Comment by ThePoetics** [comment]
Yes, using pip version 23.3.2

**Comment by fecet** [comment]
Could you try the version from `pip install git+https://github.com/fecet/moxtrice.git`?

**Comment by ThePoetics** [comment]
Unfortunately I'm seeing the same error

![image](https://github.com/fecet/moxtrice/assets/87587068/77e7a266-e8ab-43a6-a34a-4cea55a941dd)

**Comment by ThePoetics** [comment]
I'd love to share this tool with my local gaming group if we can get over this bug

**Comment by fecet** [comment]
Could you try the latest github version and report the output?
I don't use windows so cannot address this quickly.

**Comment by ThePoetics** [comment]
Unfortunately the latest github version still errors out on me (same issue) on Windows, but it seems the `pip install` version works on *nix.

**Comment by fecet** [comment]
The recent commit was not made to solve a problem, but to identify the cause of the problem, as I added some logs.

**Comment by ThePoetics** [comment]
Ah, thank you. I re-ran `pip install` and got the following error when running moxtrice:

![image](https://github.com/fecet/moxtrice/assets/87587068/a3bb31aa-8607-46f0-8054-4a3b21f56827)

**Comment by matterramun** [comment]
I'm able to reproduce the same result from @ThePoetics most recent comment.

**Comment by ThePoetics** [comment]
Unfortunately I'm still seeing the same error, even after updating to 0.1.dev13

![image](https://github.com/fecet/moxtrice/assets/87587068/23eb668a-80bb-4351-8535-ae2880d09af9)

**Comment by fecet** [comment]
@ThePoetics Have you tried the git version?

**Comment by ThePoetics** [comment]
It looks like running it from the drive it's installed on does work as expected. Thank you!
